// Creates a variable that is used for all of the endpoints.
@Excersise3_HostAddress = https://localhost:7090

# Defines a POST request.
POST {{Excersise3_HostAddress}}/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###
Get {{Excersise3_HostAddress}}/todoitems

###
GET {{Excersise3_HostAddress}}/todoitems/1

###

# Defines a PUT request.
PUT {{Excersise3_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{Excersise3_HostAddress}}/todoitems/1

###
